### ISSUE TITLE
UI Improvements Task List

### ISSUE THREAD

**Issue by Soulstices** [Soulstices/checked-todo-app#5]
- [ ] Add scroll to bottom button inside StickyBar for reversed layout.
- [ ] Add an option to make TaskCreator fixed while scrolling the task list.
- [ ] Add an indication that the link has been copied after clicking on "Share" button inside StickyBar.
- [ ] Fix an issue where using one long word as a task's text would stretch the UI.
